name: reva_bites
description: A food ordering application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  razorpay_flutter: ^1.4.0
  fluttertoast: ^8.2.4
  sign_in_with_apple: ^6.1.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png